---
additional:
- template-docker

files:
- '!README.md'
- '!.secrets.baseline'
- '!.github/pull.yml'
- '!.github/template-sync.yml'
- '!.github/workflows/pre-commit-update.yml'
- '!.github/settings.yml'
